#!/bin/bash
echo -e "\n
Привет, чувак! Я найду для тебя расположение нужного тебе слова во ВСЕХ офисных файлах этой папки. \n
Если всосал фишку, напиши здеся - что ищешь \n"
read response
find . -name "*.doc" | 
while read i; do catdoc "$i" | 
grep --color=auto -iH --label="$i" "$response"; done

find . -name "*.docx" | 
while read i; do docx2txt < "$i" | 
grep --color=auto -iH --label="$i" "$response"; done

find . -name "*.xls" | 
while read i; do xls2csv "$i" | 
grep --color=auto -iH --label="$i" "$response"; done

find . -name "*.xlsx" | 
while read i; do xlsx2csv "$i" | 
grep --color=auto -iH --label="$i" "$response"; done

find . -name "*.pdf" | 
while read i; do less "$i" | 
grep --color=auto -iH --label="$i" "$response"; done